### ISSUE TITLE
distance_in_km_level bug with not_null arg

### ISSUE THREAD

**Issue by chloepugh** [moj-analytical-services/splink#917] opened 2022-12-01 16:35 UTC
### What happens?

Having `not_null=True` as an argument of the `distance_in_km_level` comparison level causes the error message `ParseError: Expecting ). Line 1, Col: 17. ("lat_r" is not null` at this stage: https://github.com/moj-analytical-services/splink/blob/c90505182f66e4750835a426c767ce1621b91221/splink/comparison_level_library.py#L304

If the `not_null` argument is omitted then the code works.

### To Reproduce

```
import pandas as pd
import numpy as np
from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.duckdb_comparison_library as cl
import splink.duckdb.duckdb_comparison_level_library as cll

# Define some dummy data
df = pd.DataFrame({
    'unique_id': [
        1, 2, 3, 4,
        5, 6, 7, 8,
        9, 10, 11, 12,
        13, 14, 15, 16,
    ],
    'forenames': [
        'Homer', 'marge', 'PATTY', '',
        '.', 'C.B.', '   kent', 'NED',
        'charles-montgomery', 'waylon', '01234', 'Billy',
        'Homer', 'Marge', 'PATTY', 'Selma',
    ],
    'surname': [
        'SIMPSON', 'simpson', 'BOUVIER', 'selma bouvier',
        'Duffman', 'Guy', 'brockman...', 'FLAN*DERS',
        'burns', 'smithers', np.nan, 'Paul',
        'SIMPSON', 'Simpson', 'Bouvier', 'Bouvier',
    ],
    'postcode': [
        'SW1A 0AA', 'AA10 1AA.', 'AA11 1AC', 'AA11  1AB',
        'N/A', 'USA', '1234', 'AA10',
        'ZZ14 1AA 400', 'ZZ14 2AA', np.nan, np.nan,
        'SW1A 0AA', 'SW1A 0AA', 'A11 1AB', 'AA11 1AB',
    ],
    'lat': [
        50.19, 51.0, 51.02, 51.01,
        np.nan, np.nan, np.nan, 51.0,
        51.55, 51.55, np.nan, np.nan,
        50.19, 50.19, 51.01, 51.02,
    ],
    'long': [
        -2.10, -3.70, -3.72, -3.71,
        np.nan, np.nan, np.nan, -3.70,
        -4.23, -4.23, np.nan, np.nan,
        -2.10, -2.10, -3.71, -3.72,
    ],
})


# Splink settings
settings = {
    "unique_id_column_name": "unique_id",
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.forenames = r.forenames and l.surname = r.surname",
        "l.postcode = r.postcode",
    ],
    "comparisons": [
        cl.exact_match("forenames", term_frequency_adjustments=False),
        cl.exact_match("surname", term_frequency_adjustments=False),
        # Custom comparison for postcodes
        {
            "output_column_name": "postcode",
            "comparison_levels": [
                cll.null_level("postcode"),
                cll.exact_match_level("postcode", term_frequency_adjustments=True),
                cll.distance_in_km_level('lat', 'long', 5, not_null=True),
                cll.else_level(),
            ],
        }
    ],
}

# Set up the linker
linker = DuckDBLinker(df, settings)

linker.estimate_u_using_random_sampling(target_rows=1e3)

blocking_rule = "l.forenames = r.forenames"
training_session = linker.estimate_parameters_using_expectation_maximisation(blocking_rule)

```

### OS:

MoJ Analytical Platform

### Splink version:

3.4.3

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment] 2022-12-02 10:08
This looks like it is probably the same issue as #894 - if so that has been fixed in #901, which will appear in the next release (which I imagine will be fairly soon).

Have you tried running this on the current version on master (`pip install splink --upgrade --pre`)?  Do let me know if that is not working.

**Comment by chloepugh** [comment] 2022-12-02 10:26
Cheers, hopefully it's just that then.

I have tried running after doing `pip install splink --upgrade --pre` but it still doesn't work. It still says the version of splink is 3.4.3, if that sounds correct?

**Comment by ThomasHepworth** [comment] 2022-12-02 14:31
I can confirm this has now been fixed. I'll add a new release so users can apply the fix.

**Closed by ThomasHepworth** 2022-12-02 14:31 UTC
