### ISSUE TITLE
Double Column Fuzzy Match 

### ISSUE THREAD

**Issue by firmai** [moj-analytical-services/splink#1045] opened 2023-02-13 18:03 UTC
This is a great and very flexible solution from what I can see from the documentation. Currently I do still think the examples could be better layed out. For one I am interested in a very easy fuzzy match of two columns a company name, and a ticker symbol. I have been attempting multiple different configurations and I am unable to solve this problem, but I am positive that this is something your library can do. If you already has a fuzzy matching example like the one described, would you mind pointing me to it? 

Thanks again,
Derek

**Comment by aalexandersson** [comment] 2023-02-14 23:37
Disclaimer: I am only a relatively new user of `splink`.

What did you try, and which error did you get?

The documentation at [https://moj-analytical-services.github.io/splink/](https://moj-analytical-services.github.io/splink/) is not clear if only two columns are acceptable. Can you add one or two more columns to link on? Otherwise, I am not sure what is the issue here?

**Comment by NickCrews** [comment] 2023-02-15 18:24
If I understand your task, I don't think splink would currently work well for you, because your two features, company name and ticker symbol, are going to be highly correlated. See https://github.com/moj-analytical-services/splink#what-data-does-splink-work-best-with.

Splink doesn't work with highly correlated columns because
1. it relies on bayes theorem, which assumes uncorrelated columns. with two correlated columns, if you get a good match score for one column, you're probably going to get a good match score for the other column as well, so you are effectively "double counting" this evidence, even though it really is only a single piece of evidence.
2. it relies on uncorrelatedness to do the unsupervised training with Expectation Maximization (EM).

A maintainer should confirm/correct me here, but I think your options to get around these two problems are
- for 1, you need to only have one Comparsion which accounts for the information in both columns. Don't have a separate Comparison for each.
- for 2, you can use ground truth labels to train the m and u parameters, instead of relying on EM.

**Comment by RossKen** [comment] 2023-03-14 17:09
Yes I can confirm that @NickCrews answer is correct, therefore I am going to close this issue for now.

**Closed by RossKen** 2023-03-14 17:09 UTC
Labels: enhancement
