### ISSUE TITLE
DuckDB - Invalid Input Error: Failed to cast value: Unimplemented type for cast (VARCHAR -> NULL)

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#1024] opened 2023-02-06 14:37 UTC
### What happens?

Where a dataframe column that's loaded into `DuckDB` is predominantly made up of NULL values, queries appear to fail.

Attempting to recreate this bug using only `forenames = [None, None, None, 'john', None]` (5 rows) as your input column, won't break duckdb. However, when you multiply this by some large value, queries will suddenly start failing with the resulting error:
`Invalid Input Error: Failed to cast value: Unimplemented type for cast (VARCHAR -> NULL)`

It may be worthwhile testing if loading dataframes from `pyarrow` resolves this issue [as is posited here](https://github.com/moj-analytical-services/splink/issues/680).

I haven't looked far enough into this to work out what's wrong or how to potentially resolve this.

### To Reproduce

```
import pandas as pd
import duckdb

forenames = [None, None, None, 'john', None]*1000

data = {
    'id': range(0,len(forenames)),
    'forename': forenames
}
df = pd.DataFrame(data)
# csv_name = "hmmm.csv"
# df.to_csv(csv_name, index=False)
# df = pd.read_csv(csv_name)
df.dtypes


con = duckdb.connect()
con.register("test", df)

con.execute("select * from test")
con.execute("select * from test limit 1")  # this breaks
con.execute("select * from test").fetch_df()  # as does this
```

### OS:

iOS

### Splink version:

3.6.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zslade** [comment] 2023-02-07 11:39
Haven't got to the bottom of this yet but here's a fix, converting the `pandas` dataframe to a `pyarrow` table before querying with `DuckDB`:

```
import pandas as pd
import duckdb
import pyarrow as pa

forenames = [None, None, None, 'john', None]*1000

data = {
    'id': range(0,len(forenames2)),
    'forename': forenames2
}
df = pd.DataFrame(data)

# pandas to arrow table
test_arrow = pa.Table.from_pandas(df)

test_arrow

con = duckdb.connect()
con.execute("select * from test_arrow").fetch_df() # this works

# This also works and resembles the code execute by Splink
#con.query("select * from test_arrow").to_df()
```

**Comment by zslade** [comment] 2023-02-07 12:18
The problem seems to occur when the column **starts with `None`** AND **contains > 1000 rows** AND **contains other (non-numeric) datatypes**. For example:

```
forenames = [None, 'jack', ]*1000 # this breaks

forenames = ['jack', None]*1000 # this works
forenames = [None, 'john']*999 # this works
forenames = [None, 5]*1000 # this works
```
When it works, `forename` column is of type VARCHAR:

```
import pandas as pd
import duckdb

forenames = ['jack', None]*1000

data = {
    'id': range(0,len(forenames)),
    'forename': forenames
}
df = pd.DataFrame(data)

con = duckdb.connect()
con.query("select * from df")
```
When it doesn't work, `forename` column is of type INTEGER:

```
import pandas as pd
import duckdb

forenames = [None, 'john']*1000

data = {
    'id': range(0,len(forenames)),
    'forename': forenames
}
df = pd.DataFrame(data)

con = duckdb.connect()
con.query("select * from df")
```

**Comment by ThomasHepworth** [comment] 2023-02-07 13:08
@zslade see [this](https://duckdb.org/docs/guides/python/import_pandas.html).

**Comment by zslade** [comment] 2023-02-07 13:42
Aha!

Including `con.execute("SET GLOBAL pandas_analyze_sample=1001")` fixes the toy example, without needing to resort to `pyarrow`

**Comment by ThomasHepworth** [comment] 2023-02-07 14:01
Could you implement a fix within [the duckdb linker](https://github.com/moj-analytical-services/splink/blob/master/splink/duckdb/duckdb_linker.py) when you get a chance?

**Comment by NickCrews** [comment] 2023-02-15 18:34
> Including con.execute("SET GLOBAL pandas_analyze_sample=1001") fixes the toy example, without needing to resort to pyarrow

Nice! But the final solution needs to be more stable, as this would fail if you gave it 1001 rows (or for whatever N you choose, it would fail for N+1)

See https://duckdb.org/docs/guides/python/import_pandas.html#object-columns, the problem is that you are passing in a DF of type object. If they are of type "string" before passing to duckdb, then there is no ambiguity. You could
1. refuse to accept DFs with type object (easiest for us, harder for users, but they probably need to be thinking about it)
2. call df.convert_dtypes() before passing to duckdb. Perhaps there are situations where this would cast incorrectly??
3. Set pandas_analyze_sample to len(df) + 1. Easy for users, but possibly slow??

**Comment by ThomasHepworth** [comment] 2023-02-16 10:13
Thanks a lot for your insights, Nick.

I sat down with Zoe on Monday to discuss this, but we only had a limited pool of time. The plan is to revisit this next Monday when we are both in the office again.

I'm cautious about implementing a `len(df)+1` fix, as, as you say, we could run into performance issues on linker initialisation.

However, we won't know until we test this.

**Comment by zslade** [comment] 2023-02-23 14:04
Thanks for your suggestions Nick!

Tom and I have explored these options now.

Calling `df.convert_dtypes()`before passing to DuckDB doesn’t seem to work overall. The conversion from `object` type to `string` type works but still DuckDB’s interpretation of the column’s datatype fails:

```
import pandas as pd
import duckdb
import time

forenames = [None, 'jack']*1_000

data = {
    'id': range(0,len(forenames)),
    'forename': forenames
}
df = pd.DataFrame(data)

display(df.dtypes)

df = df.convert_dtypes()

display(df.dtypes)

con = duckdb.connect()

con.register("df_test", df)
con.query("select * from df")

sql = """
DESCRIBE df_test
"""
con.execute(sql).fetch_df()
```

We have tested setting `pandas_analyze_sample` to `len(df)+1` for a range of `len(df)`:

```
import pandas as pd
import duckdb
import time

forenames = [None, 'jack']*100_000

data = {
    'id': range(0,len(forenames)),
    'forename': forenames
}
df = pd.DataFrame(data)

n=len(df)

start_time = time.time()

con = duckdb.connect()
con.execute(f"SET GLOBAL pandas_analyze_sample={n+1}")

con.register("df_test", df)
con.query("select * from df")

time.time() - start_time
```
**Timings:**
| **len(df)** | **runtime (s)** |
|-------------|-----------------|
| 1000        | ~0.01           |
| 10,000      | ~0.03           |
| 100,000     | ~0.19           |
| 1,000,000   | ~1.84           |
| 10,000,000  | ~20.02          |
| 50,000,000  | ~100.00         |

As you suspected, this starts to get slow as the number of rows gets large, and the times are only going to get longer for a more realistic dataframe with many `object` type columns. And given that `object` type columns are commonly used in data linking, I think option 1 wouldn't be ideal.

So currently we have two potential ways forward:
- Adjust `pandas_analyze_sample`, but perhaps this is going to negatively impact performance too much?
- Convert pandas dataframes to pyarrow tables, but this means including another dependency with Splink

(or maybe there's a better solutions we've not considered.)

@RobinL do you have any thoughts on the best way to proceed?

**Comment by NickCrews** [comment] 2023-02-23 18:17
Good research, thanks!! Thats useful to see the timings. That's surprising to me that duckdb doesnt correctly cast string dtypes. I would even call this a bug, should we file an issue with duckdb?

I would be curious is pyarrow is already a transitive dependency of splink, eg does duckdb already require it? I would go to lengths to avoid adding it as a dependency.

What about option C:
1. call convert_dtype()s
2. pass to duckdb
3. see if there are any strings after convert_dtypes(), if so, do an explicit cast within duckdb

Other option D) is to force users to pass in an explicit schema for what they want their DF to be interpreted as.

**Comment by RobinL** [comment] 2023-02-25 20:12
Is it possible pandas 2.0 is going to help here?

![image](https://user-images.githubusercontent.com/2608005/221377643-1a243aaf-613b-4dcc-826e-d13c980c411b.png)
https://datapythonista.me/blog/pandas-20-and-the-arrow-revolution-part-i

**Comment by zslade** [comment] 2023-03-07 11:07
Thanks @NickCrews and @RobinL 

We tested your suggestion C Nick, but `DuckDB` still isn’t happy - it appears to try to infer datatypes before the cast and so still fails.

For now, we have included a message to the user explaining the error and suggesting the temporary workaround of converting their dataframe to a `pyarrow` table.

Hopefully the ability to access a `pyarrow` backend in `pandas` 2.0 will provide a longer term solution 🤞 .

**Comment by RossKen** [comment] 2023-09-05 11:02
Warning added and solved by pandas 2 (when we get there) so closing issue

**Closed by RossKen** 2023-09-05 11:02 UTC
Labels: bug, duckdb
