### ISSUE TITLE
Error producing charts after estimating u- and m- probabilities

### ISSUE THREAD

**Issue by James-Osmond** [moj-analytical-services/splink#1207] opened 2023-04-27 12:03 UTC
### What happens?

I'm getting this particular error after training u- and m-probabilities in a linkage model. I produce `m_u_interactive_history_charts` with no problem, then go on to a make a `parameter_estimate_comparisons_chart`, which fails. I get the same error for `m_u_paramters_chart`s (oddly) and `match_weights_chart`s too.

I thought it might be that somewhere one of my m- or u-probabilities was 0, negative or greater than 1, but that's not the case. Does anyone have any other suggestions?

If I save the settings dictionary to a .json and reload, I can produce the latter two charts.

![splink_paramter_estimates](https://user-images.githubusercontent.com/85510689/234852043-b67483ec-437b-4173-8a1a-76d91c43ac17.png)

### To Reproduce

I am not able to provide reproducible code, somewhat unhelpfully.

### OS:

Windows 10

### Splink version:

3.6.0 and 3.8.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RossKen** [comment] 2023-09-12 11:09
Unable to reproduce so closing this issue

**Closed by RossKen** 2023-09-12 11:09 UTC
Labels: bug

**Comment by ADBond** [comment] 2023-09-20 09:12
I think I have ended up reproducing this problem - will open a fresh issue with details.
